import type { Project } from './site-media';
export const projects: Project[] = [
  {
    name: 'Mirkoz Vending',
    url: 'https://www.mirkozvending.com/',
    category: 'Website · Vending',
    theme: '#b7c7bd',
    image: '/brisk/websites/mirkozvending.jpg',
  },
  {
    name: 'SANAE Align & Glow',
    url: 'https://sanae-align.com/',
    category: 'Website · Beauty & wellness',
    theme: '#d7c8b8',
    image: '/brisk/websites/sanae-align.jpg',
  },
  {
    name: 'Landelijk Glas',
    url: 'https://www.landelijkglas.be/',
    category: 'Website · Interieur',
    theme: '#bdc4b7',
    image: '/brisk/websites/landelijkglas.jpg',
  },
  {
    name: 'Roetfilterkopen',
    url: 'https://www.roetfilterkopen.com/',
    category: 'Webshop · Auto-onderdelen',
    theme: '#c1bcd6',
    image: '/brisk/websites/roetfilterkopen.jpg',
  },
  {
    name: 'Fileservice Chiptuning',
    url: 'https://www.fileservicechiptuning.com/',
    category: 'Website · Tuning files',
    theme: '#b8becb',
    image: '/brisk/websites/fileservicechiptuning.jpg',
  },
  {
    name: 'PriveGlas',
    url: 'https://priveglas.be/',
    category: 'Website · Smart film',
    theme: '#c1cbc2',
    image: '/brisk/websites/priveglas.jpg',
  },
  {
    name: 'X Performance',
    url: 'https://x-performance.be/',
    category: 'Website · Automotive',
    theme: '#b5b8c3',
    image: '/brisk/websites/x-performance.jpg',
  },
  {
    name: 'LegacyCristal',
    url: 'https://www.legacycristal.com/',
    category: 'Webshop · Gepersonaliseerde kristallen',
    theme: '#adbdb4',
    image: '/brisk/websites/legacycristal.jpg',
  },
  {
    name: 'HP Chiptuningfiles',
    url: 'https://hp-chiptuningfiles.com/',
    category: 'Website · Tuning files',
    theme: '#c4c0a1',
    image: '/brisk/websites/hp-chiptuningfiles.jpg',
  },
  {
    name: 'Comfort Solutions',
    url: 'https://www.comfortsolutions.be/',
    category: 'Website · Wooncomfort',
    theme: '#d6c8b9',
    image: '/brisk/websites/comfortsolutions.jpg',
  },
  {
    name: 'Vestra Armor',
    url: 'https://www.vestra-armor.com/',
    category: 'Website · Events & transport',
    theme: '#b1c0c0',
    image: '/brisk/websites/vestra-armor.jpg',
  },
  {
    name: 'Roetfilter Service',
    url: 'https://www.roetfilterservice.be/',
    category: 'Website · Automotive',
    theme: '#c1cdae',
    image: '/brisk/websites/roetfilterservice.jpg',
  },
  {
    name: 'ECU Performance',
    url: 'https://ecuperformance.be/',
    category: 'Website · Automotive',
    theme: '#b7c5ce',
    image: '/brisk/websites/ecuperformance.jpg',
  },
  {
    name: 'AdBlueexpert',
    url: 'https://adblueexpert.be/',
    category: 'Website · Automotive',
    theme: '#cfc8a7',
    image: '/brisk/websites/adblueexpert.jpg',
  },
  {
    name: 'TCKO',
    url: 'https://www.tcko.be/',
    category: 'Website · Tegels & interieur',
    theme: '#c7beb0',
    image: '/brisk/websites/tcko.jpg',
  },
  {
    name: 'City Housing',
    url: 'https://www.city-housing.be/',
    category: 'Website · Hospitality',
    theme: '#c4c8b1',
    image: '/brisk/websites/city-housing.jpg',
  },
  {
    name: 'Roetfilter laten reinigen',
    url: 'https://www.roetfilterlatenreinigen.be/',
    category: 'Website · Automotive',
    theme: '#cad0b6',
  },
];
